### ISSUE TITLE
Replace google-images plugin with the npm script

### ISSUE THREAD

**Issue by thiagogabriel** [Helabs/hubot#18]
The current one is broken with #.png on the end of the image.
We should use https://github.com/hubot-scripts/hubot-google-images

**Comment by lunks** [comment]
Ha, so that's where the `#.png` comes from?

**Comment by thiagogabriel** [comment]
@lunks yes, but maybe it is not fixed yet. When did it start?

**Comment by lunks** [comment]
It has bothered me for ages! :weary:
I thought this was a weird technique to prevent hotlinking those images, mostly because depending on the search, there was no `#.png` appended to the URL.
